KiemDuyetPhamMem_ThucHanh_SoTietKiem/KiemDuyetPhamMem_ThucHanh_SoTietKiem/Controllers/SoTietKiemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KiemDuyetPhamMem_ThucHanh_SoTietKiem;

namespace KiemDuyetPhamMem_ThucHanh_SoTietKiem.Controllers
{
    public class SoTietKiemsController : Controller
    {
        private Entities db = new Entities();

        // GET: SoTietKiems
        public ActionResult Index()
        {
            var soTietKiems = db.SoTietKiems.Include(s => s.AspNetUser);
            return View(soTietKiems.ToList());
        }

        // GET: SoTietKiems/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                SoTietKiem soTietKiem = db.SoTietKiems.Find(id);
                if (soTietKiem == null)
                {
                    return HttpNotFound();
                }
                ViewBag.IdSoTietKiem = id;
                return View(soTietKiem);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            
        }

        // GET: SoTietKiems/Create
        public ActionResult Create()
        {
            ViewBag.Id_User = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: SoTietKiems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdSoTietKiem,Id_User,TenNganHang,NgayGui,SoTienGoc,KyHan,LaiSuat,LaiSuatKhongKyHan,TraLai,KhiDenHan,TinhTrang")] SoTietKiem soTietKiem)
        {
            if (ModelState.IsValid)
            {
                if (soTietKiem.LaiSuatKhongKyHan == null)
                {
                    soTietKiem.LaiSuatKhongKyHan = 0.05;
                }
                db.SoTietKiems.Add(soTietKiem);
                db.SaveChanges();
                TempData["message"] = "<b>Thêm thành công</b>:<br> ID sổ: " + soTietKiem.TenNganHang + "_" + soTietKiem.IdSoTietKiem + "<br>Số tiền gốc: " + soTietKiem.SoTienGoc + "<br>Kỳ hạn: " + soTietKiem.KyHan;
                TempData["MessageSuccess"] = "<script>document.getElementById('thongbaoThanhCong').style.display = 'block';</script>";
                return View("Index");
            }
            ViewBag.Id_User = new SelectList(db.AspNetUsers, "Id", "Email", soTietKiem.Id_User);
            return View(soTietKiem);
        }
        public ActionResult Them1()
        {
            ViewBag.Id_User = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: SoTietKiems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Them1(string tenNganHang , DateTime ngaygui,string id_user)
        {
            try
            {
                SoTietKiem soTietKiem = new SoTietKiem();
                soTietKiem.Id_User = id_user;
                soTietKiem.TenNganHang = tenNganHang;
                soTietKiem.NgayGui = ngaygui;


                soTietKiem.TinhTrang = "Chưa hoàn thiện";
                soTietKiem.SoTienGoc = 0;
                soTietKiem.KyHan = "";
                soTietKiem.LaiSuat = 0;

                soTietKiem.LaiSuatKhongKyHan = 0;
                soTietKiem.TraLai = "";
                soTietKiem.KhiDenHan = "";

                soTietKiem.TienLai = 0;

            
                db.SoTietKiems.Add(soTietKiem);
                db.SaveChanges();
                TempData["message"] = "<b>lưu thành công</b>";
                TempData["MessageSuccess"] = "<script>document.getElementById('thongbaoThanhCong').style.display = 'block';</script>";
                ViewBag.IdSoTietKiem = soTietKiem.IdSoTietKiem;
                return View("Them2",soTietKiem);
            }
            catch
            {
                TempData["message"] = "Thao tác thất bại";
                TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                return RedirectToAction("Index");
            }

        }
        public ActionResult Them2(int? id)
        {
            try
            {
                SoTietKiem soTietKiem = db.SoTietKiems.Find(id);
                if (soTietKiem == null)
                {
                    TempData["message"] = "Thao tác thất bại";
                    TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                    return View("Index");
                }
                ViewBag.IdSoTietKiem = id;
                return View(soTietKiem);
            }
            catch
            {
                TempData["message"] = "Thao tác thất bại";
                TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                return RedirectToAction("Index");
            }
        }

        // POST: SoTietKiems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Them2(int id_sotietkiem,decimal soTienGoc, string kyHan, double laiSuat)
        {
            try
            {
                SoTietKiem soTietKiem = db.SoTietKiems.Find(id_sotietkiem);
                soTietKiem.SoTienGoc = soTienGoc;
                soTietKiem.KyHan = kyHan;
                soTietKiem.LaiSuat = laiSuat;
            
                db.Entry(soTietKiem).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "<b>lưu thành công</b>";
                TempData["MessageSuccess"] = "<script>document.getElementById('thongbaoThanhCong').style.display = 'block';</script>";
                ViewBag.IdSoTietKiem = soTietKiem.IdSoTietKiem;
                return View("Them3", soTietKiem);
            }
            catch
            {
                TempData["message"] = "Thao tác thất bại";
                TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                return RedirectToAction("Index");
            }

        }
        public ActionResult Them3(int? id)
        {
            try
            {
                SoTietKiem soTietKiem = db.SoTietKiems.Find(id);
                if (soTietKiem == null)
                {
                    TempData["message"] = "Thao tác thất bại";
                    TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                    return View("Index");
                }
                ViewBag.IdSoTietKiem = id;
                return View(soTietKiem);
            }
            catch
            {
                TempData["message"] = "Thao tác thất bại";
                TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                return RedirectToAction("Index");
            }
        }

        // POST: SoTietKiems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Them3(int id_sotietkiem, double laiSuatKhongKyHan,string traLai, string khiDenHan)
        {
            try
            {
                SoTietKiem soTietKiem = db.SoTietKiems.Find(id_sotietkiem);
                soTietKiem.LaiSuatKhongKyHan = laiSuatKhongKyHan;
                soTietKiem.TraLai = traLai;
                soTietKiem.KhiDenHan = khiDenHan;
                soTietKiem.TinhTrang = "Mở"; 
            
                db.Entry(soTietKiem).State = EntityState.Modified;
                db.SaveChanges();
                TempData["message"] = "<b>Thêm thành công</b>:<br> ID sổ: " + soTietKiem.TenNganHang + "_" + soTietKiem.IdSoTietKiem + "<br>Số tiền gốc: " + soTietKiem.SoTienGoc + "<br>Kỳ hạn: " + soTietKiem.KyHan;
                TempData["MessageSuccess"] = "<script>document.getElementById('thongbaoThanhCong').style.display = 'block';</script>";
                ViewBag.IdSoTietKiem = soTietKiem.IdSoTietKiem;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["message"] = "Thao tác thất bại";
                TempData["MessageWarning"] = "<script>document.getElementById('thongbaoThatBai').style.display = 'block';</script>";
                return RedirectToAction("Index");
            }

        }
        public ActionResult CreateNganHang()
        {
            
            return View();
        }

        // POST: SoTietKiems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNganHang(string tenNganHangKhac,string id_user)
        {
            NganHangCuaUser nganhangmoi = new NganHangCuaUser();

KiemDuyetPhamMem_ThucHanh_SoTietKiem/KiemDuyetPhamMem_ThucHanh_SoTietKiem/Views/Shared/_FormLoginRegsister.cshtml

@model KiemDuyetPhamMem_ThucHanh_SoTietKiem.Models.RegisterViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<style>
    body {
        background-color: #267836;
    }

    .mySlides {
        display: none;
    }

    .text {
        color: #f2f2f2;
        font-size: 20px;
        padding: 8px 12px;
        position: absolute;
        bottom: 8px;
        width: 100%;
        text-align: center;
    }

    .numbertext {
        color: #f2f2f2;
        font-size: 12px;
        padding: 8px 12px;
        position: absolute;
        top: 0;
    }

    .dot {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
    }

    .dotactive {
        cursor: pointer;
        height: 15px;
        width: 15px;
        margin: 0 2px;
        background-color: #123419;
        border-radius: 50%;
        display: inline-block;
        transition: background-color 0.6s ease;
    }
</style>
<body>

    <h2 class="w3-center">Money Lover</h2>

    <div class="w3-content w3-display-container" style="width:400px">
        <div class="mySlides w3-animate-opacity">
            <div class="numbertext">1 / 5</div>
            <img class="" src="~/Content/hinhanh/1.png" style="width:100%">
            <div class="text">Quản lý tài chính hiệu quả với MoneyLover</div>
        </div>
        <div class="mySlides w3-animate-opacity">
            <div class="numbertext">2 / 5</div>
            <img class="disabled" src="~/Content/hinhanh/2.png" style="width:100%">
            <div class="text">Quản lý chi tiêu cá nhân và hoàn thiện mục tiêu tài chính</div>
        </div>
        <div class="mySlides w3-animate-opacity">
            <div class="numbertext">3 / 5</div>
            <img class="disabled" src="~/Content/hinhanh/3.png" style="width:100%">
            <div class="text">Dễ dàng truy cập dữ liệu Money Lover trên nhiều thiết bị</div>
        </div>
        <div class="mySlides w3-animate-opacity">
            <div class="numbertext">4 / 5</div>
            <img class="disabled" src="~/Content/hinhanh/4.png" style="width:100%">
            <div class="text">Kiểm soát từng khoản thu chi với hệ thống báo cáo chi tiết</div>
        </div>
        <div class="mySlides w3-animate-opacity">
            <div class="numbertext">5 / 5</div>
            <img class="disabled" src="~/Content/hinhanh/5.png" style="width:100%">
            <div class="text">Lên kế hoạc tài chính thông minh và từng bước tiết kiệm để hiện thực hóa ước mơ</div>
        </div>

        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
    </div>
    <br />
    <div style="text-align:center">
        <span id="dot1" class="dot dotactive" onclick="showslide(1); dotactive(1)"></span>
        <span id="dot2" class="dot" onclick="showslide(2); dotactive(2)"></span>
        <span id="dot3" class="dot" onclick="showslide(3); dotactive(3)"></span>
        <span id="dot4" class="dot" onclick="showslide(4); dotactive(4)"></span>
        <span id="dot5" class="dot" onclick="showslide(5); dotactive(5)"></span>

    </div>
    <br />

    <div class="w3-content w3-display-container" style="width:400px">
        <button type="button" class=" btn btn-default btn-lg btn-block" style="color:#267836" onclick="document.getElementById('id04').style.display='block'">LẦN ĐẦU SỰ DỤNG MONEY LOVER </button>
    </div>
    <br />
    <div class="w3-content w3-display-container" style="width:400px">
        <button type="button" class=" btn btn-success btn-lg btn-block" onclick="document.getElementById('id03').style.display='block'">ĐÃ SỬ DỤNG MONEY LOVER </button>
    </div>
    @*FORM đăng nhập*@
    <div id="id03" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-bottom" style="max-width:500px">
            <div class="w3-container">
                <section id="loginForm">
                    <div class="w3-center">
                        <br>
                        <span onclick="document.getElementById('id03').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
                        <div class="w3-margin-top">
                            <h1>
                                Đăng nhập bằng tài khoản email
                            </h1>
                        </div>
                    </div>
                    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <h4></h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="col-md-3"><b>Email</b></label>
                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.Email, new { @class = "w3-input w3-margin-bottom" })
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3"><b>Mật khẩu</b></label>
                            <div class="col-md-9">
                                @Html.PasswordFor(m => m.Password, new { @class = "w3-input w3-margin-bottom" })
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                            </div>
                        </div>
                        <button class=" btn btn-success btn-lg btn-block w3-margin-bottom" type="submit">
                            ĐĂNG NHẬP
                        </button>

                        @* Enable this once you have account confirmation enabled for password reset functionality
                            <p>
                                @Html.ActionLink("Forgot your password?", "ForgotPassword")
                            </p>*@
                    }
                    <button class=" btn btn-default btn-lg btn-block w3-margin-bottom" type="submit"
                            onclick="document.getElementById('id04').style.display = 'block';document.getElementById('id03').style.display = 'none'">
                        ĐĂNG KÝ
                    </button>

                </section>
            </div>

        </div>
    </div>
    @*FORM ĐĂNG Ký*@
    <div id="id04" class="w3-modal">
        <div class="w3-modal-content w3-card-4 w3-animate-bottom" style="max-width:500px">
            <div class="w3-container">
                <section id="loginForm">
                    <div class="w3-center">
                        <br>
                        <span onclick="document.getElementById('id04').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
                        <div class="w3-margin-top">
                            <h1>
                                Đăng ký bằng tài khoản email.
                            </h1>
                        </div>
                    </div>
                    @using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <h4></h4>
                        <hr />
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="col-md-3"><b>Email</b></label>

                            <div class="col-md-9">
                                @Html.TextBoxFor(m => m.Email, new { @class = "w3-input w3-margin-bottom" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3"><b>Mật khẩu</b></label>
                            <div class="col-md-9">
                                @Html.PasswordFor(m => m.Password, new { @class = "w3-input w3-margin-bottom" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3"><b>Nhập lại mật khẩu</b></label>
                            <div class="col-md-9">
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "w3-input w3-margin-bottom" })
                            </div>
                        </div>
                        <button class=" btn btn-success btn-lg btn-block w3-margin-bottom" type="submit">
                            ĐĂNG KÝ
                        </button>
                    }

                    <button class=" btn btn-default btn-lg btn-block w3-margin-bottom" type="submit"
                            onclick="document.getElementById('id03').style.display = 'block';document.getElementById('id04').style.display = 'none'">
                        ĐĂNG NHẬP
                    </button>

                </section>
            </div>

        </div>
    </div>






    <script>
        var slideIndex = 1;
        showDivs(slideIndex);
        dotactive(slideIndex);
        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            x[slideIndex - 1].style.display = "block";

            $('#dot1').removeClass('dotactive');
            $('#dot2').removeClass('dotactive');
            $('#dot3').removeClass('dotactive');
            $('#dot4').removeClass('dotactive');
            $('#dot5').removeClass('dotactive');
            $('#dot' + (slideIndex).toString()).addClass('dotactive');
        }
        function showslide(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");

            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            x[n - 1].style.display = "block";

        }
        function dotactive(n) {
            $('#dot1').removeClass('dotactive');
            $('#dot2').removeClass('dotactive');
            $('#dot3').removeClass('dotactive');
            $('#dot4').removeClass('dotactive');
            $('#dot5').removeClass('dotactive');
            $('#dot' + n.toString()).addClass('dotactive');
        }
    </script>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

KiemDuyetPhamMem_ThucHanh_SoTietKiem/KiemDuyetPhamMem_ThucHanh_SoTietKiem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{
    if (Request.IsAuthenticated == false)
    {
        Response.Redirect("~/Home", false);
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/bootstrap/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- DataTables CSS -->
    <link href="~/Content/bootstrap/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/bootstrap/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/bootstrap/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/bootstrap/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/Content/w3.css">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
@*class="w3-light-grey"*@
<body class="w3-light-gray">
    <!-- Navbar -->
    <div class="w3-top">
        <div class="w3-bar w3-green w3-card">
            <a class="w3-bar-item w3-button w3-padding-large w3-hide-medium w3-hide-large w3-right" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
            @Html.ActionLink("Money Lover", "Index", "SoTietKiems", new object { }, new { @class = "w3-bar-item w3-button w3-padding-large w3-hide-small" })
            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" ,@class= "w3-bar-item w3-button w3-padding-large w3-hide-small" })

            @*<div class="w3-dropdown-hover w3-hide-small">
            <button class="w3-padding-large w3-button" title="More">MORE <i class="fa fa-caret-down"></i></button>
            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                <a href="#" class="w3-bar-item w3-button">Merchandise</a>
                <a href="#" class="w3-bar-item w3-button">Extras</a>
                <a href="#" class="w3-bar-item w3-button">Media</a>
            </div>
        </div>*@
            <a class="w3-button w3-padding-large w3-hover-red w3-hide-small w3-right" onclick="document.getElementById('ThongBaoDangXuat').style.display='block'">Đăng Xuất</a>
        </div>
    </div>

    <!-- Navbar on small screens (remove the onclick attribute if you want the navbar to always show on top of the content when clicking on the links) -->
    <div id="navDemo" class="w3-bar-block w3-green w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:44px">
        <a class="w3-bar-item w3-button w3-padding-large" onclick="document.getElementById('ThongBaoDangXuat').style.display='block'">Đăng Xuất</a>
    </div>


    <!-- !PAGE CONTENT!  class="w3-main w3-light-gray"  -->
    <div class="w3-container w3-light-gray">
        @RenderBody()
        <!-- End page content -->
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <div id="ThongBaoDangXuat" class="w3-modal" style="display:none">
        <div class="w3-modal-content login-panel panel panel-default w3-animate-zoom w3-light-gray" style="max-width:400px;margin-top:10%">
            <div class="w3-container">
                <section id="loginForm">
                    <div class="">
                        <br>
                        <span onclick="document.getElementById('ThongBaoDangXuat').style.display='none'" class="w3-button w3-xlarge w3-transparent w3-display-topright" title="Close Modal">×</span>
                        <div class="">
                            <h4>
                                Confirm !
                            </h4>
                            <hr />
                        </div>
                    </div>

                    <div class="w3-padding">
                        <div class="form-group">
                            <img src="~/Content/hinhanh/warning.png" class="col-md-4  w3-margin-bottom w3-image" />
                            <div class=" col-md-8">
                                <p>Bạn có muốn đăng xuất?</p>
                            </div>
                        </div>
                        <br />
                        <div class="w3-container form-group">
                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="col-sm-6">
                                    <a href="javascript:document.getElementById('logoutForm').submit()" class="w3-hover-blue-gray btn w3-blue btn-lg btn-block w3-margin-bottom ">Có</a>
                                </div>

                            }
                            <div class="col-sm-6">
                                <button onclick="document.getElementById('ThongBaoDangXuat').style.display='none'" class=" btn btn-default btn-lg btn-block w3-margin-bottom ">
                                    Không
                                </button>
                            </div>

                        </div>

                    </div>
                </section>
            </div>

        </div>
    </div>
</body>
</html>
<script>
    // Used to toggle the menu on small screens when clicking on the menu button
    function myFunction() {
        var x = document.getElementById("navDemo");
        if (x.className.indexOf("w3-show") == -1) {
            x.className += " w3-show";
        } else {
            x.className = x.className.replace(" w3-show", "");
        }
    }

    // When the user clicks anywhere outside of the modal, close it
    var modal = document.getElementById('ticketModal');
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
